from typing import Any, Callable, Generator, Generic, NoReturn, TypeVar, overload

_I = TypeVar("_I")
_T = TypeVar("_T", covariant=True)
_V = TypeVar("_V", covariant=True)
_K = TypeVar("_K", covariant=True)
_U = TypeVar("_U", covariant=True)
_W = TypeVar("_W", covariant=True)

class Parser(Generic[_T]):
    def map(self, func: Callable[[_T], _V]) -> Parser[_V]: ...
    def at_most(self, n: int) -> Parser[list[_T]]: ...
    def at_least(self, n: int) -> Parser[list[_T]]: ...
    def many(self) -> Parser[list[_T]]: ...
    @overload
    def optional(self) -> Parser[_T | None]: ...
    @overload
    def optional(self, default: _I) -> Parser[_T | _I]: ...
    def parse(self, stream: str) -> _T: ...
    def parse_partial(self, stream: str) -> tuple[_T, str]: ...
    def sep_by(
        self, separator: Parser[_V], min: int = 0, max: int = int(float("inf"))
    ) -> Parser[list[_T]]: ...
    def desc(self, description: str) -> Parser[_T]: ...
    def __rshift__(self, other: Parser[_V]) -> Parser[_V]: ...
    def __lshift__(self, other: Parser[_V]) -> Parser[_T]: ...
    def __or__(self, other: Parser[_V]) -> Parser[_T | _V]: ...

def generate(
    func: Callable[[], Generator[Any, Any, _V]],
) -> Parser[_V]: ...
def string(
    string: str, transform: Callable[[str], str] | None = None
) -> Parser[str]: ...
def string_from(
    *strings: str, transform: Callable[[str], str] | None = None
) -> Parser[str]: ...
def regex(string: str) -> Parser[str]: ...
def fail(message: str) -> Parser[NoReturn]: ...
@overload
def seq(p1: Parser[_T]) -> Parser[_T]: ...
@overload
def seq(p1: Parser[_T], p2: Parser[_V]) -> Parser[tuple[_T, _V]]: ...
@overload
def seq(
    p1: Parser[_T], p2: Parser[_V], p3: Parser[_K]
) -> Parser[tuple[_T, _V, _K]]: ...
@overload
def seq(
    p1: Parser[_T], p2: Parser[_V], p3: Parser[_K], p4: Parser[_U]
) -> Parser[tuple[_T, _V, _K, _U]]: ...
@overload
def seq(
    p1: Parser[_T], p2: Parser[_V], p3: Parser[_K], p4: Parser[_U], p5: Parser[_W]
) -> Parser[tuple[_T, _V, _K, _U, _W]]: ...
